# GrowthFlow Customer Retention Strategy Optimization

## Day 2 – Data Loading & Quality Check

### Objective
Load the five datasets, inspect their structure, and assess their initial data quality before further analysis.

## 2.1 Import Required Libraries

In [90]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

import sqlite3

## 2.2 Load the Datasets

In [96]:
# Read the GrowthFlow datasets into pandas DataFrames

customer_info = pd.read_csv("growthflow_customer_information.csv")
monthly_status = pd.read_csv("growthflow_monthly_status.csv")
usage_data = pd.read_csv("growthflow_usage_data.csv")
engagement_data = pd.read_csv("growthflow_engagement_data.csv")
feedback_data = pd.read_csv("growthflow_feedback_data.csv")


# Store the datasets in a dictionary for easier access and iteration

datasets = {
    "Customer Information": customer_info,
    "Monthly Status": monthly_status,
    "Usage Data": usage_data,
    "Engagement Data": engagement_data,
    "Feedback Data": feedback_data
}

## 2.3 Initial Data Inspection
This section provides an initial inspection of each dataset by reviewing sample records, dataset dimensions, column names, and data types to verify that the data has been loaded correctly and is ready for further analysis.

In [110]:
# Display the first five rows of each dataset

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    display(df.head(5))

============================================================
Customer Information
============================================================

,customer_id,subscription_date,cohort,industry,region,customer_type,plan_type,company_size
0,CUST_00001,2024-04-12,2024-04-01,Finance,Europe,Mid-market,Basic,171
1,CUST_00002,2025-04-11,2025-04-01,Finance,Europe,SMB,Basic,24
2,CUST_00003,2024-05-10,2024-05-01,Education,Latin America,SMB,Enterprise,2
3,CUST_00004,2024-07-10,2024-07-01,Technology,Europe,Enterprise,Enterprise,3404
4,CUST_00005,2025-07-14,2025-07-01,Education,Latin America,SMB,Basic,15

============================================================
Monthly Status
============================================================

,customer_id,cohort,activity_month,months_since_sub,is_active,monthly_revenue,customer_type,plan_type,region,industry
0,CUST_00001,2024-04-01,2024-04-01,0,1,49,Mid-market,Basic,Europe,Finance
1,CUST_00001,2024-04-01,2024-05-01,1,1,49,Mid-market,Basic,Europe,Finance
2,CUST_00001,2024-04-01,2024-06-01,2,1,49,Mid-market,Basic,Europe,Finance
3,CUST_00001,2024-04-01,2024-07-01,3,1,49,Mid-market,Basic,Europe,Finance
4,CUST_00001,2024-04-01,2024-08-01,4,1,49,Mid-market,Basic,Europe,Finance

============================================================
Usage Data
============================================================

,customer_id,activity_month,months_since_sub,session_duration,feature_crm,feature_email_campaigns,feature_analytics,feature_automation,feature_advanced_analytics,feature_custom_workflows
0,CUST_00001,2024-04-01,0,23,1,0,1,1,0,0
1,CUST_00001,2024-05-01,1,31,1,3,1,0,0,0
2,CUST_00001,2024-06-01,2,31,2,2,1,1,0,0
3,CUST_00001,2024-07-01,3,41,1,1,1,1,0,0
4,CUST_00001,2024-08-01,4,63,1,0,1,0,0,0

============================================================
Engagement Data
============================================================

,customer_id,engagement_month,engagement_count,response_rate,avg_response_rate
0,CUST_00001,2024-12-01,1,1.0,0.55
1,CUST_00001,2025-01-01,1,0.0,0.55
2,CUST_00001,2025-02-01,1,1.0,0.55
3,CUST_00001,2025-03-01,1,1.0,0.61
4,CUST_00001,2025-05-01,1,0.0,0.55

============================================================
Feedback Data
============================================================

  customer_id feedback_month  satisfaction_score  nps_score feedback_category
0  CUST_00003     2024-10-01                   7         30           Product
1  CUST_00003     2024-08-01                   7         28          Features
2  CUST_00008     2025-11-01                   9         33           Product
3  CUST_00009     2025-06-01                   8         34          Features
4  CUST_00012     2025-07-01                   7         34           Product

In [105]:
# Display the number of rows and columns in each dataset

for name, df in datasets.items():
    rows, columns = df.shape

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print(f"Rows: {rows}")
    print(f"Columns: {columns}")

============================================================
Customer Information
============================================================
Rows: 5000
Columns: 8

============================================================
Monthly Status
============================================================
Rows: 54021
Columns: 10

============================================================
Usage Data
============================================================
Rows: 54021
Columns: 10

============================================================
Engagement Data
============================================================
Rows: 14532
Columns: 5

============================================================
Feedback Data
============================================================
Rows: 1447
Columns: 5

In [104]:
# Display the column names in each dataset

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print(df.columns.tolist())

============================================================
Customer Information
============================================================
['customer_id', 'subscription_date', 'cohort', 'industry', 'region', 'customer_type', 'plan_type', 'company_size']

============================================================
Monthly Status
============================================================
['customer_id', 'cohort', 'activity_month', 'months_since_sub', 'is_active', 'monthly_revenue', 'customer_type', 'plan_type', 'region', 'industry']

============================================================
Usage Data
============================================================
['customer_id', 'activity_month', 'months_since_sub', 'session_duration', 'feature_crm', 'feature_email_campaigns', 'feature_analytics', 'feature_automation', 'feature_advanced_analytics', 'feature_custom_workflows']

============================================================
Engagement Data
============================================================
['customer_id', 'engagement_month', 'engagement_count', 'response_rate', 'avg_response_rate']

============================================================
Feedback Data
============================================================
['customer_id', 'feedback_month', 'satisfaction_score', 'nps_score', 'feedback_category']

In [103]:
# Display the structure and data types of each dataset

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    df.info()

============================================================
Customer Information
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   object
 1   subscription_date  5000 non-null   object
 2   cohort             5000 non-null   object
 3   industry           5000 non-null   object
 4   region             5000 non-null   object
 5   customer_type      5000 non-null   object
 6   plan_type          5000 non-null   object
 7   company_size       5000 non-null   int64
dtypes: int64(1), object(7)
memory usage: 312.6+ KB

============================================================
Monthly Status
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54021 entries, 0 to 54020
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       54021 non-null  object
 1   cohort            54021 non-null  object
 2   activity_month    54021 non-null  object
 3   months_since_sub  54021 non-null  int64
 4   is_active         54021 non-null  int64
 5   monthly_revenue   54021 non-null  int64
 6   customer_type     54021 non-null  object
 7   plan_type         54021 non-null  object
 8   region            54021 non-null  object
 9   industry          54021 non-null  object
dtypes: int64(3), object(7)
memory usage: 4.1+ MB

============================================================
Usage Data
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54021 entries, 0 to 54020
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 54021 non-null  object
 1   activity_month              54021 non-null  object
 2   months_since_sub            54021 non-null  int64
 3   session_duration            54021 non-null  int64
 4   feature_crm                 54021 non-null  int64
 5   feature_email_campaigns     54021 non-null  int64
 6   feature_analytics           54021 non-null  int64
 7   feature_automation          54021 non-null  int64
 8   feature_advanced_analytics  54021 non-null  int64
 9   feature_custom_workflows    54021 non-null  int64
dtypes: int64(8), object(2)
memory usage: 4.1+ MB

============================================================
Engagement Data
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14532 entries, 0 to 14531
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        14532 non-null  object
 1   engagement_month   14532 non-null  object
 2   engagement_count   14532 non-null  int64
 3   response_rate      14532 non-null  float64
 4   avg_response_rate  14532 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 567.8+ KB

============================================================
Feedback Data
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1447 entries, 0 to 1446
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         1447 non-null   object
 1   feedback_month      1447 non-null   object
 2   satisfaction_score  1447 non-null   int64
 3   nps_score           1447 non-null   int64
 4   feedback_category   1447 non-null   object
dtypes: int64(2), object(3)
memory usage: 56.7+ KB

## 2.4 Data Quality Assessment
This section assesses the datasets for missing values and duplicate records that could affect the accuracy and reliability of the analysis.

In [106]:
# Check for missing values in each dataset

for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print(df.isnull().sum())

============================================================
Customer Information
============================================================
customer_id          0
subscription_date    0
cohort               0
industry             0
region               0
customer_type        0
plan_type            0
company_size         0
dtype: int64

============================================================
Monthly Status
============================================================
customer_id         0
cohort              0
activity_month      0
months_since_sub    0
is_active           0
monthly_revenue     0
customer_type       0
plan_type           0
region              0
industry            0
dtype: int64

============================================================
Usage Data
============================================================
customer_id                   0
activity_month                0
months_since_sub              0
session_duration              0
feature_crm                   0
feature_email_campaigns       0
feature_analytics             0
feature_automation            0
feature_advanced_analytics    0
feature_custom_workflows      0
dtype: int64

============================================================
Engagement Data
============================================================
customer_id          0
engagement_month     0
engagement_count     0
response_rate        0
avg_response_rate    0
dtype: int64

============================================================
Feedback Data
============================================================
customer_id           0
feedback_month        0
satisfaction_score    0
nps_score             0
feedback_category     0
dtype: int64

In [111]:
# Check for duplicate records in each dataset

duplicate_summary = []

for name, df in datasets.items():
    duplicate_summary.append({
        "Dataset": name,
        "Duplicate Records": df.duplicated().sum()
    })

pd.DataFrame(duplicate_summary)

                Dataset  Duplicate Records
0  Customer Information                  0
1        Monthly Status                  0
2            Usage Data                  0
3       Engagement Data                  0
4         Feedback Data                  0

## 2.5 Data Quality Summary

The initial data quality assessment indicates that all five GrowthFlow datasets were successfully loaded and are suitable for further analysis. The dataset structures, dimensions, column names, and data types were verified. No missing values or duplicate records were identified across the datasets, suggesting that the data is complete and consistent. While most data types are appropriate, date-related columns are currently stored as object data types and will be converted to the appropriate datetime format during the data preprocessing stage.